name: Docker Manager Image
on: workflow_call

jobs:

  manager-image:
    name: Manager image
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8
        with:
          name: or-manager-build
          path: manager/build/install/manager
      - name: Install QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4
        with:
          platforms: linux/amd64,linux/aarch64
      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1
      - name: Build manager image
        run: |
          docker buildx build --build-arg GIT_COMMIT=${{ github.sha }} --platform linux/amd64,linux/aarch64 -t openremote/manager:test-ci manager/build/install/manager
          docker buildx build --build-arg GIT_COMMIT=${{ github.sha }} --platform linux/amd64 -t openremote/manager:develop-${{ github.sha }} --output type=docker,dest=or_manager.tar manager/build/install/manager
      - name: Archive OpenRemote Manager
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: or-manager-image
          if-no-files-found: error
          path: or_manager.tar
